name: silk-road-author-id
dependencies:
  - python=3.7
  - conda-forge::jupyterlab
  - bokeh::jupyter_bokeh
  - conda-forge::notebook
  - anaconda::ipykernel
  - click
  - matplotlib
  - bs4
  - pandas
  - pip
  - pip:
    - tensorflow==2.1.0
